{{- if .Values.route.enabled -}}
{{- $fullName := include "<sample>.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $host := .Values.route.host -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "<sample>.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ $host }}
  port:
    targetPort: {{ $svcPort }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  to:
    kind: Service
    name: {{ $fullName }}
{{- end }}
